parameters:
    avatarDirectory: '/public/avatars'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\RegistrationController:
        arguments:
            $avatarDirectory: '%avatarDirectory%'

    App\Twig\UrlEncryptionExtension:
        arguments:
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
        tags:
            - { name: twig.extension }

    App\Repository\FreelancerProfileRepository:
        autowire: true
        autoconfigure: true
        public: false